services:
  client:
    image: mintam141/talckatoo-client:ff0629852223e335449fb89b688e57f42cc61ef8 # Use env var for prod image, fallback to local for dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_AI_ASSISTANT_ID=${VITE_AI_ASSISTANT_ID}
      - VITE_AI_ASSISTANT_CALL=${VITE_AI_ASSISTANT_CALL}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_WHISPER_TRANSCRIPTION_URL=${VITE_WHISPER_TRANSCRIPTION_URL}
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}
      - VITE_GOOGLE_URL=${VITE_GOOGLE_URL}
      - VITE_ENCRYPTION_KEY=${VITE_ENCRYPTION_KEY}
      - VITE_ENCRYPTION_IV=${VITE_ENCRYPTION_IV}
      - VITE_KEK_SECRET=${VITE_KEK_SECRET}
      - VITE_AZURE_TRANSLATOR_KEY=${VITE_AZURE_TRANSLATOR_KEY}
      - VITE_TRANSLATOR_ENDPOINT=${VITE_TRANSLATOR_ENDPOINT}
    restart: unless-stopped
# Last updated: Wed Feb 12 18:56:12 UTC 2025
# Last updated: Thu Feb 13 03:20:36 UTC 2025
# Last updated: Thu Feb 13 18:04:57 UTC 2025
