services:
  client:
    image: mintam141/talckatoo-client:latest # Use env var for prod image, fallback to local for dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
# Last updated: Wed Feb 12 18:56:12 UTC 2025
# Last updated: Thu Feb 13 03:20:36 UTC 2025
# Last updated: Thu Feb 13 18:04:57 UTC 2025
# Last updated: Thu Feb 13 19:03:20 UTC 2025
# Last updated: Thu Feb 13 19:22:01 UTC 2025
# Last updated: Thu Feb 13 19:31:25 UTC 2025
# Last updated: Thu Feb 13 20:19:33 UTC 2025
# Last updated: Thu Feb 13 20:45:33 UTC 2025
# Last updated: Thu Feb 13 21:04:12 UTC 2025
