services:
  client:
    image: mintam141/talckatoo-client:latest # Use env var for prod image, fallback to local for dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_AI_ASSISTANT_ID=${VITE_AI_ASSISTANT_ID}
      - VITE_AI_ASSISTANT_CALL=${VITE_AI_ASSISTANT_CALL}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_WHISPER_TRANSCRIPTION_URL=${VITE_WHISPER_TRANSCRIPTION_URL}
      - VITE_BASE_URL=https://talckatoo-250985c83f7c.herokuapp.com/api/v1
      - VITE_SOCKET_URL=https://talckatoo-250985c83f7c.herokuapp.com
      - VITE_GOOGLE_URL=https://talckatoo-250985c83f7c.herokuapp.com/api/v1/account/loginWithGoogle 
      - VITE_ENCRYPTION_KEY=${VITE_ENCRYPTION_KEY}
      - VITE_ENCRYPTION_IV=${VITE_ENCRYPTION_IV}
      - VITE_KEK_SECRET=${VITE_KEK_SECRET}
      - VITE_AZURE_TRANSLATOR_KEY=${VITE_AZURE_TRANSLATOR_KEY}
      - VITE_TRANSLATOR_ENDPOINT=${VITE_TRANSLATOR_ENDPOINT}
    restart: unless-stopped
# Last updated: Wed Feb 12 18:56:12 UTC 2025
# Last updated: Thu Feb 13 03:20:36 UTC 2025
# Last updated: Thu Feb 13 18:04:57 UTC 2025
# Last updated: Thu Feb 13 19:03:20 UTC 2025
# Last updated: Thu Feb 13 19:22:01 UTC 2025
# Last updated: Thu Feb 13 19:31:25 UTC 2025
# Last updated: Thu Feb 13 20:19:33 UTC 2025
