version: "3.8"

services:
  vite-app:
    image: test_1
    ports:
      - "5173:5173"
    secrets:
      - ai_assistant_id
      - ai_assistant_call
      - openai_api_key
      - whisper_url
      - base_url
      - socket_url
      - google_url
      - encryption_key
      - encryption_iv
      - kek_secret
      - azure_translator_key
      - translator_endpoint
    environment:
      VITE_AI_ASSISTANT_ID_FILE: /run/secrets/ai_assistant_id
      VITE_AI_ASSISTANT_CALL_FILE: /run/secrets/ai_assistant_call
      VITE_OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      VITE_WHISPER_TRANSCRIPTION_URL_FILE: /run/secrets/whisper_url
      VITE_BASE_URL_FILE: /run/secrets/base_url
      VITE_SOCKET_URL_FILE: /run/secrets/socket_url
      VITE_GOOGLE_URL_FILE: /run/secrets/google_url
      VITE_ENCRYPTION_KEY_FILE: /run/secrets/encryption_key
      VITE_ENCRYPTION_IV_FILE: /run/secrets/encryption_iv
      VITE_KEK_SECRET_FILE: /run/secrets/kek_secret
      VITE_AZURE_TRANSLATOR_KEY_FILE: /run/secrets/azure_translator_key
      VITE_TRANSLATOR_ENDPOINT_FILE: /run/secrets/translator_endpoint

secrets:
  ai_assistant_id:
    external: true
  ai_assistant_call:
    external: true
  openai_api_key:
    external: true
  whisper_url:
    external: true
  base_url:
    external: true
  socket_url:
    external: true
  google_url:
    external: true
  encryption_key:
    external: true
  encryption_iv:
    external: true
  kek_secret:
    external: true
  azure_translator_key:
    external: true
  translator_endpoint:
    external: true
