services:
  vite-app:
    image: talckatoo-frontend:latest
    ports:
      - "5173:5173"
    secrets:
      - client_ai_assistant_id
      - ai_assistant_call
      - client_openai_api_key
      - whisper_url
      - base_url
      - socket_url
      - google_url
      - client_encryption_key
      - client_encryption_iv
      - client_kek_secret
      - client_azure_translator_key
      - client_translator_endpoint
    environment:
      VITE_AI_ASSISTANT_ID: /run/secrets/client_ai_assistant_id
      VITE_AI_ASSISTANT_CALL: /run/secrets/ai_assistant_call
      VITE_OPENAI_API_KEY: /run/secrets/client_openai_api_key
      VITE_WHISPER_TRANSCRIPTION_URL: /run/secrets/whisper_url
      VITE_BASE_URL: /run/secrets/base_url
      VITE_SOCKET_URL: /run/secrets/socket_url
      VITE_GOOGLE_URL: /run/secrets/google_url
      VITE_ENCRYPTION_KEY: /run/secrets/client_encryption_key
      VITE_ENCRYPTION_IV: /run/secrets/client_encryption_iv
      VITE_KEK_SECRET: /run/secrets/client_kek_secret
      VITE_AZURE_TRANSLATOR_KEY: /run/secrets/client_azure_translator_key
      VITE_TRANSLATOR_ENDPOINT: /run/secrets/client_translator_endpoint
    restart: unless-stopped

secrets:
  client_ai_assistant_id:
    external: true
  ai_assistant_call:
    external: true
  client_openai_api_key:
    external: true
  whisper_url:
    external: true
  base_url:
    external: true
  socket_url:
    external: true
  google_url:
    external: true
  client_encryption_key:
    external: true
  client_encryption_iv:
    external: true
  client_kek_secret:
    external: true
  client_azure_translator_key:
    external: true
  client_translator_endpoint:
    external: true