services:
  client:
    image: mintam141/talckatoo-client:3764e1aaafed5f88f4d4cb62048285ba2d939c76
    ports:
      - "5173:5173"
    environment:
      - VITE_AI_ASSISTANT_ID=${VITE_AI_ASSISTANT_ID}
      - VITE_AI_ASSISTANT_CALL=${VITE_AI_ASSISTANT_CALL}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_WHISPER_TRANSCRIPTION_URL=${VITE_WHISPER_TRANSCRIPTION_URL}
      - VITE_BASE_URL=https://talckatoo-250985c83f7c.herokuapp.com/api/v1
      - VITE_SOCKET_URL=https://talckatoo-250985c83f7c.herokuapp.com
      - VITE_GOOGLE_URL=https://talckatoo-250985c83f7c.herokuapp.com/api/v1/account/loginWithGoogle
      - VITE_ENCRYPTION_KEY=${VITE_ENCRYPTION_KEY}
      - VITE_ENCRYPTION_IV=${VITE_ENCRYPTION_IV}
      - VITE_KEK_SECRET=${VITE_KEK_SECRET}
      - VITE_AZURE_TRANSLATOR_KEY=${VITE_AZURE_TRANSLATOR_KEY}
      - VITE_TRANSLATOR_ENDPOINT=${VITE_TRANSLATOR_ENDPOINT}
    restart: unless-stopped# Last updated: Wed Feb 12 04:04:02 UTC 2025
# Last updated: Wed Feb 12 04:05:18 UTC 2025
# Last updated: Wed Feb 12 04:06:33 UTC 2025
# Last updated: Wed Feb 12 04:07:48 UTC 2025
# Last updated: Wed Feb 12 04:09:03 UTC 2025
# Last updated: Wed Feb 12 04:10:19 UTC 2025
# Last updated: Wed Feb 12 04:11:46 UTC 2025
# Last updated: Wed Feb 12 04:13:01 UTC 2025
# Last updated: Wed Feb 12 04:14:23 UTC 2025
# Last updated: Wed Feb 12 04:22:41 UTC 2025
# Last updated: Wed Feb 12 04:24:01 UTC 2025
# Last updated: Wed Feb 12 04:25:19 UTC 2025
# Last updated: Wed Feb 12 04:26:35 UTC 2025
# Last updated: Wed Feb 12 04:27:58 UTC 2025
# Last updated: Wed Feb 12 04:29:13 UTC 2025
# Last updated: Wed Feb 12 04:30:35 UTC 2025
# Last updated: Wed Feb 12 04:31:57 UTC 2025
# Last updated: Wed Feb 12 04:33:20 UTC 2025
# Last updated: Wed Feb 12 04:35:04 UTC 2025
# Last updated: Wed Feb 12 04:36:28 UTC 2025
# Last updated: Wed Feb 12 04:37:45 UTC 2025
# Last updated: Wed Feb 12 04:39:08 UTC 2025
# Last updated: Wed Feb 12 15:41:37 UTC 2025
