version: "3.8"

services:
  vite-app:
    image: mintam141/talckatoo-client:latest # Pulls latest image from Docker Hub
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./secrets:/run/secrets:ro 
    secrets:
      - ai_assistant_id
      - ai_assistant_call
      - openai_api_key
      - whisper_url
      - base_url
      - socket_url
      - google_url
      - encryption_key
      - encryption_iv
      - kek_secret
      - azure_translator_key
      - translator_endpoint

secrets:
  ai_assistant_id:
    file: ./secrets/ai_assistant_id.txt
  ai_assistant_call:
    file: ./secrets/ai_assistant_call.txt
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  whisper_url:
    file: ./secrets/whisper_url.txt
  base_url:
    file: ./secrets/base_url.txt
  socket_url:
    file: ./secrets/socket_url.txt
  google_url:
    file: ./secrets/google_url.txt
  encryption_key:
    file: ./secrets/encryption_key.txt
  encryption_iv:
    file: ./secrets/encryption_iv.txt
  kek_secret:
    file: ./secrets/kek_secret.txt
  azure_translator_key:
    file: ./secrets/azure_translator_key.txt
  translator_endpoint:
    file: ./secrets/translator_endpoint.txt
# Last updated: Mon Feb 17 02:06:25 UTC 2025
# Last updated: Mon Feb 17 02:26:12 UTC 2025
# Last updated: Mon Feb 17 03:28:52 UTC 2025
