services:
  client:
    image: mintam141/talckatoo-client:f324731a7eb940f9b9764b39c5c05f584f98df13 # Use env var for prod image, fallback to local for dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
# Last updated: Wed Feb 12 18:56:12 UTC 2025
# Last updated: Thu Feb 13 03:20:36 UTC 2025
# Last updated: Thu Feb 13 18:04:57 UTC 2025
# Last updated: Thu Feb 13 19:03:20 UTC 2025
# Last updated: Thu Feb 13 19:22:01 UTC 2025
# Last updated: Thu Feb 13 19:31:25 UTC 2025
# Last updated: Thu Feb 13 20:19:33 UTC 2025
# Last updated: Thu Feb 13 20:45:33 UTC 2025
# Last updated: Thu Feb 13 21:04:12 UTC 2025
# Last updated: Thu Feb 13 22:03:25 UTC 2025
# Last updated: Fri Feb 14 03:37:39 UTC 2025
# Last updated: Mon Feb 17 01:57:55 UTC 2025
