name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: yourusername
  IMAGE_NAME: talckatoo-client
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update docker-compose.prod.yml
        run: |
          # Update image tag in docker-compose.prod.yml
          sed -i "s|\${IMAGE_TAG:-latest}|${{ env.IMAGE_TAG }}|g" docker-compose.prod.yml
          
          # Add timestamp to force update
          echo "# Last updated: $(date)" >> docker-compose.prod.yml

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add docker-compose.prod.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Docker image tag to ${IMAGE_TAG}" && git push)
